# Generated by Django 5.1.7 on 2025-03-15 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_video_video_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='release_date',
        ),
        migrations.AddField(
            model_name='movie',
            name='cast',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='movie',
            name='category',
            field=models.CharField(choices=[('trilogy', 'Trilogy'), ('sequel', 'Sequel'), ('standalone', 'Standalone'), ('series', 'Series')], default='standalone', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='duration',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='movie',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='release_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='series',
            field=models.CharField(default='standalone', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('trilogy', 'Trilogy'), ('sequel', 'Sequel'), ('standalone', 'Standalone'), ('series', 'Series')], max_length=20)),
                ('order', models.IntegerField()),
                ('movies', models.ManyToManyField(to='api.movie')),
            ],
        ),
    ]
