# Generated by Django 5.1.6 on 2025-03-22 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_movie_release_date_movie_cast_movie_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='video_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
